/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package helloWorld;

public class App {

    private String greeting = "Hello";


    public String getGreeting(String name) {
        return "Hello "+name;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting("Akshaya"));
    }
}
